exports.lines = [
`     A          R HELP`,
`     A*%%TS  SD  20080304  144943  PGML        REL-V5R4M0  5722-WDS`,
`     A                                      KEEP`,
`     A                                      OVERLAY`,
`     A                                      WINDOW(10 2 10 70 *NORSTCSR)`,
`     A                                      WDWBORDER((*DSPATR RI) (*CHAR ':.::-`,
`     A                                      ::.:'))`,
`     A                                      WDWTITLE((*TEXT 'Print accounts by -`,
`     A                                      store number for status type - Help-`,
`     A                                      ') (*COLOR WHT))`,
`     A                                  1 26'Print accounts - Help'`,
`     A                                      COLOR(WHT)`,
`     A                                  3  3'This report print all accounts of -`,
`     A                                      selected status for a store or all'`,
`     A                                  4  2'stores.  An account will print for-`,
`     A                                       a store only if that store has'`,
`     A                                  5  2'taken a check from that account.  -`,
`     A                                      You can only select one status type'`,
`     A                                  6  2'for each report request.'`,
`     A                                  9  2'Press Enter to return'`,
]