exports.lines = [
    `     A          R TEST_REC`,
    `     A N71                                  INVITE`,
    `     A N71                                  PUTOVR`,
    `     A  71                                  OVERLAY`,
    `     A  71                                  FRCDTA`,
    `     A*`,
    `     A                                  3  2'some text (detail)'`,
    `     A            FIELD1        12A  B  3 21TEXT('MY FIELD')`,
    `     A  01N72N73                            DSPATTR(HI)`,
    `     A  72                                  DSPATTR(PR)`,
    `     A N72                                  DSPATTR(UL)`,
    `     A  01                                  DSPATTR(PC)`,
    `     A  01 72                               DSPATTR(RI)`,
    `     A  01 72                               DSPATTR(RED)`,
    `     A                                      OVRDTA`,
    `     A            FIELD2         5A  O    +2TEXT('Short')`,
    `     A*`,
    `     A                                  4  2'Option . . . . .'`,
    `     A            FIELD3    R        B  4 19REFFLD(COL1 TABPF)`,
    `     A  02N72N73                            DSPATTR(HI)`,
    `     A  72                                  DSPATTR(PR)`,
    `     A N72                                  DSPATTR(UL)`,
    `     A  02                                  DSPATTR(PC)`,
    `     A  02 72                               DSPATTR(RI)`,
    `     A  02 72                               DSPATTR(RED)`,
    `     A                                      OVRDTA`,
    `     A*`,
    `     A                                  6  2'Address . . . . .'`,
    `     A            ADDRESS      140A  B  6 19TEXT('MY FIELD')`,
    `     A  03N72N73                            DSPATTR(HI)`,
    `     A  72                                  DSPATTR(PR)`,
    `     A N72                                  DSPATTR(UL)`,
    `     A  03                                  DSPATTR(PC)`,
    `     A  03 72                               DSPATTR(RI)`,
    `     A  03 72                               DSPATTR(RED)`,
    `     A                                      OVRDTA`,
    `     A                                      CNTFLD(50)`,
    ];